### ISSUE TITLE
HI,Can this convert webp  heic to jpg or png?

### ISSUE THREAD

**Issue by basicbh** [Codrax/Delphi-Extended-Images-Format#1]
var WebImage: TWebPImage;
  var HeifImage: THeifImage;
  WebImage := TWebPImage.Create;
  HeifImage := THeifImage.Create;
  try
    // Load WebP
    WebImage.LoadFromFile('sample.webp');

    // Assign to Heif
    HeifImage.Assign(WebImage);

    // Display
    Image1.Stretch := true;
    Image1.Picture.Graphic := HeifImage;

    // Save heif
    HeifImage.SaveToFile('out.heif');
  finally
    WebImage.Free;
    HeifImage.Free;
  end;

**Comment by Codrax** [comment]
Yes It can.

The only current limitation is saving a THeifImage to a TStream, the `SaveToStream()` procedure. It's a technical limitation I was unable to implement yet, but It does not affect your use case.
